# Generated by Django 4.0.6 on 2023-05-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=20)),
                ('type', models.CharField(choices=[('Other', 'Other'), ('Car', 'Car'), ('Mobile', 'Mobile'), ('Education', 'Education'), ('House', 'House'), ('Health', 'Health')], default='Other', max_length=20)),
                ('total_amount', models.CharField(max_length=20)),
                ('initial_payment', models.CharField(max_length=20)),
                ('noti_email', models.EmailField(blank=True, default='owner@gmail.com', max_length=20)),
                ('whatsapp_no', models.CharField(max_length=15)),
                ('payment_period', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Yearly', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Insure',
            fields=[
                ('loan_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bucket.loan')),
                ('to_pay', models.CharField(max_length=20)),
            ],
            bases=('bucket.loan',),
        ),
    ]
