# Generated by Django 4.0.6 on 2023-05-23 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('insure_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bucket.insure')),
            ],
            bases=('bucket.insure',),
        ),
        migrations.AddField(
            model_name='loan',
            name='schedule_day',
            field=models.DateField(default=datetime.datetime(2023, 5, 1, 16, 12, 40, 522999)),
        ),
        migrations.AddField(
            model_name='loan',
            name='schedule_time',
            field=models.TimeField(default=datetime.datetime(2023, 5, 23, 16, 12, 40, 522999)),
        ),
        migrations.AlterField(
            model_name='loan',
            name='noti_email',
            field=models.EmailField(blank=True, default='example@gmail.com', max_length=20),
        ),
    ]
